### PR TITLE
Big progress on Landsat C2 updates

### PR DESCRIPTION
**Pull request by steeleb**
Hey Matt!

Two primary files are `LandsatC2_M4-7_SurfaceRefTempStacks.Rmd` and `LandsatC2_M8-9_SurfaceRefTempStacks.Rmd`. Note that because I changed from a Qmd to an Rmd, it looks a lot worse than it is. This is the same general workflow as before, but I've re-organized a bit and added some features. 

Major updates:

- DSWE is fixed for C2 and scaling factors! Changes here were in 0c3ea87 - these edits came from the Pitt crew, see co-author attribution.
- We extract data for specific points, but also as whole-lake values (where Lake = NHDPlus boundary) - the latter is the last code chunk in both of the '...SurfRefTempStack.Rmd' files.
- We extract for a bunch of summary statistics for each band - this is a giant pain in the code, as you have to make bands (.addBands in the RefPull function) to select bands (in the previously alluded to 'selectors' in the last two code chunks)

Notes:

- Generally speaking this is still too specific to the Northern Water Project, but NW is my test subject, so we'll cross that bridge when we get there. 
- There are a bunch of scene-level metadata things I need to add to the output, but I'm thinking about doing that in another script, since it would be redundant to do it for each lake/point in a lake, when there are multiple lakes/points in a given scene. It would also just add to the stupidity of the 'selectors' (i.e. lines 542/579 in the M4-7 .Rmd) which are already insane.
- There's some funky stuff going on in the LS8-9 script/data product: the summaries produce a higher frequency of negative reflectance values than in LS4-7. This could 100% be due to the difference in atmospheric processing between LS4-7 and LS8/9. I'll be asking Tamlin and Xiao about this tomorrow. (I'll shoot you a link via Teams, in case you're curious what I'm talking about.) I'm unsure if it's related, but the hillShadow values in the output are not 0-1, like in LS4-7 for some reason. I'll have to track this down.
- I've made a lot of edits from the original script and I need to go back and make sure that I'm getting dswe3 calcs correct, I remember a time where I would get different values for dswe and dswe3... and that is not the case here. 

Requests for this PR:

- Can you start to scheme how we might targets-ify this? I'm wondering if we need to break apart the initial 'load in location' and 'get lakes' out from all of the GEE functions for an easier targets application down the road. While this is meant to be a more general use script, I think it will serve us well to start thinking about this and the architecture of this particular set of code. This is, in part because I want to flesh out Landsat so that when we move to other satellite data we have a good jumping off point.
- The actual process here is the same as before, but we add a bunch of variables in the actual pull. I'm likely to ask Xiao to review the guts of the code in a separate PR that goes to him. That said, maybe stay big picture? Your choice there. 

THANK YOU!

### CODE REVIEW

**Review by mbrousil — APPROVED** [review]
With regards to preparing this for targets, I like the suggestion of breaking off things like the load in location process that you suggested. In general I think that a lot of the `###` level subheadings are good candidates for potential targets in most cases, though probably not all. Another thing that will be good to keep in mind is whether or not there are places where iteration or mapping can be used in the targets workflow.

**Comment by steeleb** [comment]
Thanks @mbrousil! 

Once we're ready to go there: I think breaking out 1) the location/path-row step (that would also be a time filter? See next para.), 2) the functions (since these generally won't change, but if they do, everything needs to be re-run), and 3) the task-sending (the last two chunks). 

And yes, the iteration is that last step in the code (both of the final chunks) where the 'tasks' are sent to GEE. That output gets stored in Drive and then we'll have to load it back in. There is a time lag between sending tasks and the output ending up in the Drive, though (this will be on the order of days for ASv2), and I'm not sure how/if we need to handle that on our end. There are two facets of this run that would be important for tracking in targets: both time range (probably from date of last acquisition) and space (pathrow completeness).

So that said, step 4 is probably something like checking Drive, step 5 is collating the drive files (only triggered by a change in step 4)... 

Does that sound relatively reasonable to you?

**Comment by steeleb** [comment]
I'm also going to note that the wonky hillShade numbers in LS8/9 only exist in the Drive preview of the .csv, and not when you download the file. Also the negative values for reflectance are well documented and do, indeed, have to do with the atmospheric correction that accounts for the aerosol band (B1 in LS8/9), which basically says, 'this is dark, clear water'.

**Comment by mbrousil** [comment]
Hmmm I think that working with Drive and checking statuses might be kind of tricky, but I'll need to test it out to be sure. I haven't worked with Drive through R in a while, and never with targets...Although one option is to set one of steps 4 and 5 to always run, but only if it's reasonable computationally

**Pull request merged**
